{% set name = "meshplex" %}
{% set version = "0.15.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nschloe/meshplex/archive/v{{ version }}.tar.gz
  sha256: 30d4b195478b897f1fc6fa7c42c12a07dad71bf3b37d80a40ad84f56bce22fe0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - importlib_metadata
    - python >=3.6
    - numpy >=1.9
    - scipy
    - meshio >=4,<5

test:
  imports:
    - meshplex

about:
  home: https://github.com/nschloe/meshplex
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Fast tools for simplex meshes
  doc_url: https://meshplex.readthedocs.io/
  dev_url: https://github.com/nschloe/meshplex

extra:
  recipe-maintainers:
    - rbeucher
