{% set name = "meshplex" %}
{% set version = "0.15.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nschloe/meshplex/archive/v{{ version }}.tar.gz
  sha256: b75d7759702c0cd532422dc80be3207b155597a9d1a65174e13f2472a6defe91

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - importlib_metadata
    - python
    - numpy >=1.9
    - scipy
    - meshio >=4,<5

test:
  imports:
    - meshplex

about:
  home: https://github.com/nschloe/meshplex
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Fast tools for simplex meshes
  doc_url: https://meshplex.readthedocs.io/
  dev_url: https://github.com/nschloe/meshplex

extra:
  recipe-maintainers:
    - rbeucher
